global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "api-tcc-falchi"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8085"]
        labels:
          application: "tcc-falchi"